### ISSUE TITLE
Leanplum/Leanplum.h' file not found

### ISSUE THREAD

**Issue by chiechelski** [brandingbrand/react-native-leanplum#15]
Hi there,

Any idea if I am missing any installation step?

<img width="648" alt="screen shot 2018-10-31 at 2 58 28 pm" src="https://user-images.githubusercontent.com/6915704/47762491-cb57fa80-dd21-11e8-8fe2-80133f145dba.png">

Seems to be fine on AppDelegate

<img width="340" alt="screen shot 2018-10-31 at 3 01 57 pm" src="https://user-images.githubusercontent.com/6915704/47762523-f2163100-dd21-11e8-9d04-41ca6e03b0ad.png">

And it is normally happening when I add libRNLeanplum.a oto "Link Binary With Libraries" section

Thanks for your help.

Cheers

**Comment by skyeckstrom** [comment]
Hi @chiechelski,

This package is setup so that all you should have to do is type:
```bash
react-native link "@brandingbrand/react-native-leanplum"
```

It should automatically add [the pod](https://github.com/brandingbrand/react-native-leanplum/blob/master/react-native-leanplum.podspec) as a dependency in your [Podfile](https://github.com/brandingbrand/flagship/blob/master/packages/flagship/ios/Podfile#L34) under [`# Add new pods below this line`](https://facebook.github.io/react-native/docs/linking-libraries-ios#step-2).

Let me know if those steps work for you.

**Comment by chiechelski** [comment]
Hi @skyeckstrom, 

It is working now. Thank you so much for your quick reply.

Cheers.
